In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os 

from pathlib import Path

In [3]:
# carga tablon_analitico.pickle de datos/intermedios
df = pd.read_pickle(Path("../datos/intermedios/tablon_analitico.pickle"))

In [9]:
temp = df.loc[df.evento == "purchase", ['usuario','producto']].reset_index(drop=True)
temp

          usuario  producto
0       536128518   5887011
1       536128518     34767
2       536128518     34768
3       536128518      5584
4       536128518   5588612
...           ...       ...
127559  622065819   5659905
127560  622065819   5659911
127561  622065819   5697535
127562  622065819   5699414
127563  610361057   5931773

[127564 rows x 2 columns]

In [13]:
# Sobre temp crea una lista con los 100 productos mas comprados
top_100_productos = temp['producto'].value_counts().head(100).index.tolist()
top_100_productos

[5809910,
 5854897,
 5700037,
 5304,
 5751422,
 5802432,
 5809912,
 5815662,
 5751383,
 5792800,
 5849033,
 5686925,
 5700046,
 5528035,
 5833330,
 5809911,
 5816170,
 5687151,
 5729864,
 5843836,
 5013,
 5759492,
 5622677,
 5833334,
 5800788,
 5793704,
 5561044,
 5700035,
 5549834,
 5862943,
 5587740,
 5670733,
 5783987,
 5789668,
 5615144,
 5761411,
 5833326,
 4958,
 4497,
 5773361,
 5817702,
 5776130,
 5773605,
 5857360,
 4938,
 5809871,
 5848909,
 5700039,
 5759279,
 5814046,
 5649219,
 5759491,
 5816166,
 5528034,
 5809297,
 5693501,
 5723529,
 5773606,
 5842141,
 5677043,
 5688124,
 5754853,
 5751742,
 5816172,
 5889300,
 5528051,
 5857007,
 5784897,
 5793703,
 5763238,
 5790563,
 5815730,
 5833325,
 5622687,
 5848387,
 5835924,
 5810157,
 5526,
 5836522,
 5565820,
 4768,
 5585656,
 5824810,
 5550302,
 5585658,
 4600,
 5816169,
 5854812,
 5810480,
 5742957,
 5844894,
 5833318,
 5855332,
 5724230,
 5809303,
 5749149,
 5835859,
 5749720,
 5862564,
 5833335]

In [15]:
# filtra temp para quedarte solo con los productos que estan en top_100_productos
temp_top = temp.loc[temp['producto'].isin(top_100_productos)].reset_index(drop=True)
temp_top

         usuario  producto
0      536128518   5815662
1      465338762   5817702
2      555497689   5649219
3      539216862   5854897
4      507864835   5622687
...          ...       ...
14211  582074095   5759491
14212  435564251   5802432
14213  617695004   5759491
14214  439781446   5742957
14215  589394692   5729864

[14216 rows x 2 columns]

In [16]:
# Pivota producto a columna y usuario a filas y las celdas tendran el conteo de veces el usuario compro el producto
matriz_usuario_item = temp_top.pivot_table(index='usuario', columns='producto', aggfunc='size', fill_value=0)
matriz_usuario_item

producto,4497,4600,4768,4938,4958,5013,5304,5526,5528034,5528035,...,5848909,5849033,5854812,5854897,5855332,5857007,5857360,5862564,5862943,5889300
usuario,,,,,,,,,,,,,,,,,,,,,
25392526,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50748978,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
74332980,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
80577370,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
88211255,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621646584,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
621788730,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
621925941,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
621974977,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
622021687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0